### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by gbrian** [helppery-com/meetnav-frontend-base#1]
# Help wated payable 10€ - 20€
***Please read [how to collaborate](https://github.com/helppery-com/meetnav-frontend-base) before***
[![gitter](https://icon-icons.com/icons2/2530/PNG/64/gitter_button_icon_151850.png)](https://gitter.im/meetnav/community) Let's talk

## Issue
Implement current design for Home page `/`

![image](https://user-images.githubusercontent.com/767180/107342516-94f0b480-6ac0-11eb-94f3-93618e5dfc7d.png)

Notes:
 * Add store
 * Add i18n

> This issue will be paid by sponsors
> Please post a comment below if you want to be assigned to this issue

**Comment by shahabgohar** [comment]
Yes I have seen that easily applicable

**Comment by shishir0019** [comment]
Yes, I think this is easy for me

**Comment by gbrian** [comment]
Thanks @shahabgohar, you have been assigned to the ticket. Keep here any discussion related with the task.

Thanks @shishir0019 for applying, keep notifications on, will post new tickets soon.

**Comment by shahabgohar** [comment]
Sure @gbrian

**Comment by gbrian** [comment]
Perfect @shahabgohar , clossing issue.
Pull request merged: https://github.com/helppery-com/meetnav-frontend-base/pull/2
