### ISSUE TITLE
Login Register dialog

### ISSUE THREAD

**Issue by gbrian** [helppery-com/meetnav-frontend-base#3]
# Help wanted payable
***Please read [how to collaborate](https://github.com/helppery-com/meetnav-frontend-base) before***
[![gitter](https://icon-icons.com/icons2/2530/PNG/64/gitter_button_icon_151850.png)](https://gitter.im/meetnav/community) Let's talk

## Issue
Implemente login/register dialogs

![image](https://user-images.githubusercontent.com/767180/107735105-3bc29400-6cff-11eb-82c8-4dbe7368ba78.png)

![image](https://user-images.githubusercontent.com/767180/107735180-67de1500-6cff-11eb-88d8-857e3602f8ef.png)

### Expected bahavior
From home page Login / Register section invoke dialogs
![image](https://user-images.githubusercontent.com/767180/107735300-a83d9300-6cff-11eb-890f-215153b1f72b.png)

Add new module to store `user`

*Login:* Invoke store "user" action login. Fake an async action returning user object and update state

```
{ 
 "username": "username",
 "avatar": 'https://eu.ui-avatars.com/api/?name=username"
}
```

*Register:* Invoke store "user" action register. Fake an async action, update dialog to show confirmation message

```
Please check your email to confirm your account
```

*Activation*: New route to home page `/activate/xxx-xxx-xxx-xx` where `xxx-xxx-xxx-xx` is an activation code. Fake store `user`action register with same behavior as `login` for code `xxx-xxx-xxx-ok` and show error message for `xxx-xxx-xxx-ko`

```
Invalid activation code
```

### User logged:
Update `MainLayout`accordingly
![image](https://user-images.githubusercontent.com/767180/107736013-51d15400-6d01-11eb-9944-220916c0f0e3.png)

Notes:
 * Use store for login/register actions and change state to loged user
 * Use i18n

> This issue will be paid by sponsors
> Please post a comment below if you want to be assigned to this issue

**Comment by shishir0019** [comment]
Can i get this issue to develop?
