### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by gbrian** [helppery-com/meetnav-frontend-base#4]
# Help wanted payable
***Please read [how to collaborate](https://github.com/helppery-com/meetnav-frontend-base) before***
[![gitter](https://icon-icons.com/icons2/2530/PNG/64/gitter_button_icon_151850.png)](https://gitter.im/meetnav/community) Let's talk

## Issue
Implemente search results page

![image](https://user-images.githubusercontent.com/767180/107736872-539c1700-6d03-11eb-8c19-f8905a66be6a.png)

Notes:

* Create store module `search` actions and update state with last search
  * Actions: search (topic)
  * State: { "q": "", "results": []" }  
* Use i18n

Search results example: https://github.com/helppery-com/meetnav-frontend-base/blob/281a520cb57fadef7ccb6ab3952f294ba5a53513/tests/data/search.json#L1

> This issue will be paid by sponsors
> Please post a comment below if you want to be assigned to this issue

**Comment by shahabgohar** [comment]
will do it.
assign issue

**Comment by shahabgohar** [comment]
It's almost done.
You can see the pointed arrow in the picture. I cannot tell what it is ?
kindly elaborate by sending a zoomed in image for better icon and pill description
![Screenshot_20210215_013510](https://user-images.githubusercontent.com/45337747/107888475-37c88900-6f2e-11eb-9d4d-74b07b99852f.png)
The completed task
![Screenshot_20210215_013832](https://user-images.githubusercontent.com/45337747/107888533-9c83e380-6f2e-11eb-9aaf-7c84753c4b87.png)

**Comment by gbrian** [comment]
No worries, is fine right now. Will be updated in future issues, right now having the placeholder is enough. Thanks

**Comment by gbrian** [comment]
Done by PR https://github.com/helppery-com/meetnav-frontend-base/pull/9
