### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by gbrian** [helppery-com/meetnav-frontend-base#6]
# Help wanted payable
***Please read [how to collaborate](https://github.com/helppery-com/meetnav-frontend-base) before***
[![gitter](https://icon-icons.com/icons2/2530/PNG/64/gitter_button_icon_151850.png)](https://gitter.im/meetnav/community) Let's talk

Implement profile page
![image](https://user-images.githubusercontent.com/767180/107852329-79631200-6e10-11eb-8d7a-9210a22423a1.png)

Notes:
* **Responsive**

> This issue will be paid by sponsors
> Please post a comment below if you want to be assigned to this issue

**Comment by shishir0019** [comment]
I am interested to get this

**Comment by gbrian** [comment]
Done by PR: https://github.com/helppery-com/meetnav-frontend-base/pull/8
